apiVersion: apps/v1
kind: Deployment
metadata:
  name: unithon-backend-main
  namespace: unithon
  labels:
    app: unithon-backend-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unithon-backend-main
  template:
    metadata:
      labels:
        app: unithon-backend-main
    spec:
      initContainers:
        - name: unithon-backend-main-init
          image: hyeonwoo5342/unithon-backend-main:9
          imagePullPolicy: Always
          command: ["sh", "-c", "/app/.venv/bin/python manage.py migrate"]
          envFrom:
            - secretRef:
                name: unithon-backend-main-secret
          resources:
            requests:
              memory: "200Mi"
              cpu: "150m"
            limits:
              memory: "200Mi"
              cpu: "150m"
      containers:
        - name: unithon-backend-main
          image: hyeonwoo5342/unithon-backend-main:9
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "150Mi"
              cpu: "60m"
            limits:
              memory: "150Mi"
              cpu: "60m"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 150
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 150
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: unithon-backend-main-secret
