apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaven-vod
  namespace: leaven
  labels:
    app: leaven-vod
spec:
  selector:
    matchLabels:
      app: leaven-vod
  template:
    metadata:
      labels:
        app: leaven-vod
    spec:
      containers:
      - name: leaven-vod
        image: hyeonwoo5342/leaven-vod:2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: '200Mi'
            cpu: '70m'
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 25
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
        envFrom:
        - secretRef:
            name: leaven-vod-secret
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: leaven-vod
  namespace: leaven
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leaven-vod
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
