apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmusic-fe
  namespace: haenu
  labels:
    app: vmusic-fe
spec:
  selector:
    matchLabels:
      app: vmusic-fe
  template:
    metadata:
      labels:
        app: vmusic-fe
    spec:
      containers:
      - name: vmusic-fe
        image: hyeonwoo5342/vmusic-fe:10
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: vmusic-fe-configmap
        resources:
          limits:
            memory: '300Mi'
            cpu: '100m'
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vmusic-fe
  namespace: haenu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmusic-fe
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70