apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-argocd-redis-master-0
  namespace: argocd
spec:
  storageClassName: vultr-block-storage-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
