apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitea-0
  namespace: default
spec:
  storageClassName: vultr-block-storage-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitea-postgresql-0
  namespace: default
spec:
  storageClassName: vultr-block-storage-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
