apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-stack-0
  namespace: monitoring
spec:
  storageClassName: vultr-block-storage-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
