apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-musicbook-mariadb-0
  namespace: api
spec:
  storageClassName: vultr-block-storage-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
