apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn-openvpn-as-state
  namespace: api
spec:
  storageClassName: vultr-block-storage-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
