apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-server-0
  namespace: vault
spec:
  storageClassName: vultr-block-storage-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
