apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hejhome-api
  namespace: argocd
spec:
  destination:
    name: vke-haenu
    namespace: api
    server: ''
  source:
    path: apps/api/hejhome-api
    repoURL: 'https://github.com/dokdo2013/haenu-cluster'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
