apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaven-api-temp
  namespace: api
  labels:
    app: leaven-api-temp
spec:
  selector:
    matchLabels:
      app: leaven-api-temp
  template:
    metadata:
      labels:
        app: leaven-api-temp
    spec:
      containers:
      - name: leaven-api-temp
        image: hyeonwoo5342/leaven-api-temp:1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: '250Mi'
            cpu: '100m'
          requests:
            memory: '250Mi'
            cpu: '100m'
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom: 
        - secretRef:
            name: leaven-api-temp-secret
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: leaven-api-temp
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leaven-api-temp
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
