apiVersion: apps/v1
kind: Deployment
metadata:
  name: minbird-nokduro-v2
  namespace: haenu
  labels:
    app: minbird-nokduro-v2
spec:
  selector:
    matchLabels:
      app: minbird-nokduro-v2
  template:
    metadata:
      labels:
        app: minbird-nokduro-v2
    spec:
      containers:
      - name: minbird-nokduro-v2
        image: hyeonwoo5342/minbird-nokduro-v2:32
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: '300Mi'
            cpu: '150m'
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 35
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        envFrom:
        - secretRef:
            name: minbird-nokduro-v2-secret
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: minbird-nokduro-v2
  namespace: leaven
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minbird-nokduro-v2
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
