apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaven-multi
  namespace: leaven
  labels:
    app: leaven-multi
spec:
  selector:
    matchLabels:
      app: leaven-multi
  template:
    metadata:
      labels:
        app: leaven-multi
    spec:
      containers:
      - name: leaven-multi
        image: hyeonwoo5342/leaven-multi:8
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: '20Mi'
            cpu: '10m'
          requests:
            memory: '20Mi'
            cpu: '10m'
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: leaven-multi
  namespace: leaven
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leaven-multi
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
