apiVersion: apps/v1
kind: Deployment
metadata:
  name: catolling
  namespace: legacy
  labels:
    app: catolling
spec:
  selector:
    matchLabels:
      app: catolling
  template:
    metadata:
      labels:
        app: catolling
    spec:
      containers:
      - name: catolling
        image: hyeonwoo5342/catolling:4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: '150Mi'
            cpu: '30m'
          requests:
            memory: '150Mi'
            cpu: '30m'
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catolling
  namespace: legacy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catolling
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
