apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmusic-be
  namespace: api
  labels:
    app: vmusic-be
spec:
  selector:
    matchLabels:
      app: vmusic-be
  template:
    metadata:
      labels:
        app: vmusic-be
    spec:
      containers:
      - name: vmusic-be
        image: hyeonwoo5342/vmusic-be:9
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: '200Mi'
            cpu: '100m'
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 40
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 25
          periodSeconds: 10
        envFrom:
        - secretRef:
            name: vmusic-secret
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vmusic-be
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmusic-be
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70