apiVersion: apps/v1
kind: Deployment
metadata:
  name: beadyo97-gellgell
  namespace: leaven
  labels:
    app: beadyo97-gellgell
spec:
  selector:
    matchLabels:
      app: beadyo97-gellgell
  template:
    metadata:
      labels:
        app: beadyo97-gellgell
    spec:
      containers:
      - name: beadyo97-gellgell
        image: hyeonwoo5342/beadyo97-gellgell:4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: '20Mi'
            cpu: '10m'
          requests:
            memory: '20Mi'
            cpu: '10m'
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: beadyo97-gellgell
  namespace: leaven
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: beadyo97-gellgell
  minReplicas: 2
  maxReplicas: 10
