apiVersion: apps/v1
kind: Deployment
metadata:
  name: beadyo97-gellgell
  namespace: leaven
  labels:
    app: beadyo97-gellgell
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beadyo97-gellgell
  template:
    metadata:
      labels:
        app: beadyo97-gellgell
    spec:
      containers:
      - name: beadyo97-gellgell
        image: hyeonwoo5342/beadyo97-gellgell:4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
        

