apiVersion: v1
kind: Service
metadata:
  name: beadyo97-gellgell
  namespace: leaven
  labels:
    app: beadyo97-gellgell
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: beadyo97-gellgell
