apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaven-portal
  namespace: leaven
  labels:
    app: leaven-portal
spec:
  selector:
    matchLabels:
      app: leaven-portal
  template:
    metadata:
      labels:
        app: leaven-portal
    spec:
      containers:
      - name: leaven-portal
        image: hyeonwoo5342/leaven-portal:29
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: '300Mi'
            cpu: '150m'
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 35
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        envFrom:
        - secretRef:
            name: leaven-portal-secret
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: leaven-portal
  namespace: leaven
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leaven-portal
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
