apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaven-portal
  namespace: leaven
  labels:
    app: leaven-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaven-portal
  template:
    metadata:
      labels:
        app: leaven-portal
    spec:
      containers:
        - name: leaven-portal
          image: hyeonwoo5342/leaven-portal:37
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "250Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: leaven-portal-secret
      imagePullSecrets:
        - name: dockerhub-secret
