apiVersion: apps/v1
kind: Deployment
metadata:
  name: twip-pinball
  namespace: haenu
  labels:
    app: twip-pinball
spec:
  selector:
    matchLabels:
      app: twip-pinball
  template:
    metadata:
      labels:
        app: twip-pinball
    spec:
      containers:
      - name: twip-pinball
        image: hyeonwoo5342/twip-pinball:2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # resources:
        #   limits:
        #     memory: '500Mi'
        #     cpu: '160m'
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 50
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 40
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: twip-pinball
  namespace: haenu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: twip-pinball
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70