apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitess-docs-kr
  namespace: haenu
  labels:
    app: vitess-docs-kr
spec:
  selector:
    matchLabels:
      app: vitess-docs-kr
  template:
    metadata:
      labels:
        app: vitess-docs-kr
    spec:
      containers:
      - name: vitess-docs-kr
        image: hyeonwoo5342/vitess-docs-kr:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: '20Mi'
            cpu: '10m'
          requests:
            memory: '20Mi'
            cpu: '10m'
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vitess-docs-kr
  namespace: haenu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vitess-docs-kr
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70