apiVersion: apps/v1
kind: Deployment
metadata:
  name: tewind-space
  namespace: haenu
  labels:
    app: tewind-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tewind-space
  template:
    metadata:
      labels:
        app: tewind-space
    spec:
      containers:
      - name: tewind-space
        image: hyeonwoo5342/tewind-space:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
        

