apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicbook-be
  namespace: api
  labels:
    app: musicbook-be
spec:
  selector:
    matchLabels:
      app: musicbook-be
  template:
    metadata:
      labels:
        app: musicbook-be
    spec:
      containers:
      - name: musicbook-be
        image: hyeonwoo5342/musicbook-be:2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: '300Mi'
            cpu: '200m'
          requests:
            memory: '300Mi'
            cpu: '200m'
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musicbook-be
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musicbook-be
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
