apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneymoney-front
  namespace: haenu
  labels:
    app: moneymoney-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moneymoney-front
  template:
    metadata:
      labels:
        app: moneymoney-front
    spec:
      nodeSelector:
        "vke.vultr.com/node-pool": "main-node-pool"
      containers:
      - name: moneymoney-front
        image: hyeonwoo5342/moneymoney-front:3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: '20Mi'
            cpu: '10m'
          requests:
            memory: '20Mi'
            cpu: '10m'
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: moneymoney-front
#   namespace: haenu
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: moneymoney-front
#   minReplicas: 2
#   maxReplicas: 10
