apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneymoney-front
  namespace: haenu
  labels:
    app: moneymoney-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moneymoney-front
  template:
    metadata:
      labels:
        app: moneymoney-front
    spec:
      containers:
      - name: moneymoney-front
        image: hyeonwoo5342/moneymoney-front:1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
        

