apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmusic-be
  namespace: api
  labels:
    app: vmusic-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmusic-be
  template:
    metadata:
      labels:
        app: vmusic-be
    spec:
      containers:
        - name: vmusic-be
          image: hyeonwoo5342/vmusic-be:11
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "100Mi"
              cpu: "30m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 80
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: vmusic-secret
      imagePullSecrets:
        - name: dockerhub-secret
