apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cuk-haenu-com
  namespace: argocd
spec:
  destination:
    name: vke-haenu
    namespace: legacy
    server: ''
  source:
    path: apps/legacy/cuk-haenu-com
    repoURL: 'https://github.com/dokdo2013/haenu-cluster'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
