apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatgpt
  namespace: argocd
spec:
  destination:
    name: vke-haenu
    namespace: haenu
    server: ""
  source:
    path: apps/haenu/chatgpt
    repoURL: "https://github.com/dokdo2013/haenu-cluster"
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
