apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tewind-space
  namespace: argocd
spec:
  destination:
    name: vke-haenu
    namespace: haenu
    server: ''
  source:
    path: apps/haenu/tewind-space
    repoURL: 'https://github.com/dokdo2013/haenu-cluster'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
