apiVersion: apps/v1
kind: Deployment
metadata:
  name: afdiscord-web
  namespace: haenu
  labels:
    app: afdiscord-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: afdiscord-web
  template:
    metadata:
      labels:
        app: afdiscord-web
    spec:
      containers:
      - name: afdiscord-web
        image: hyeonwoo5342/afdiscord-web:3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-secret
