apiVersion: apps/v1
kind: Deployment
metadata:
  name: hejhome-api
  namespace: api
  labels:
    app: hejhome-api
spec:
  selector:
    matchLabels:
      app: hejhome-api
  template:
    metadata:
      labels:
        app: hejhome-api
    spec:
      containers:
      - name: hejhome-api
        image: hyeonwoo5342/hejhome-api:2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: '200Mi'
            cpu: '70m'
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 35
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 25
          periodSeconds: 10
        # envFrom:
        # - secretRef:
        #     name: hejhome-api-secret
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hejhome-api
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hejhome-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70