apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gongik-ars-phone1-secret
  namespace: haenu
spec:
  encryptedData:
    PHONE_NUMBER: AgBRKgoJdOC7QL3UrFV5apylLjVds6zJZqC1hqJWz892Pdo8gND8+Np1JxFgLzHQ6tEQanUsz+eA1VaqqLs8R93bFDBiMtKQnCWNFr56rLWglv+x7hR0K7n1h0nL5UH3EJDvnDTPnNblweoZLPieJEpYvX5Fy6X3aYnAATjSVoZ4UFpcuCv8c8CN5Kp2ehItbD9RTSvmM8Sihxs5ZdIixOHN1SkPdi0KP3xFZ1wg4hYAj/wBP01Yxg1G7nF/77wqSUTVoz2NIK5RMHCQBLs3nQ2LW+5jI4dDUnU6jXiVvLv5zm5BEs2SxErB/xLyMXM9xhaVnIwKtNF33l8V2N1ArzEovyHGJKV4ZAIflNGKBQwJJYupgeLlXN+YcvItwWtxaGQ0L2xDZ2FN/JKlUHwkzTdrhEbQgAl9q/8iNc8fLDrBwEkaAZqVOZqW9laoY8U1rhqLxSgsWZbYLlc8SuGcSo1HCetFLh8NE2FhFfXws/0Poc2rgIneouBHGIUCy79YzHJ/C2TYHAu84ca04SQU/No8PxfQmV4BpUdrGmqew1K/lOJa/Kzqwqwfb7x/j/ViUgsktM2AlqTaeXXqXTfoyOR/jeFicO+RtN4kIB/BR7jb3XQEr0jsOL9mWUXYab27jpOLvPKJsdM8yOzS9DEPntwgkSQYfnPyek4gRxGSLWwrY+O68DJgx6d+hBpt3dcFqsvQSsAxriJl0VpF
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gongik-ars-phone1-secret
      namespace: haenu
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gongik-ars-phone2-secret
  namespace: haenu
spec:
  encryptedData:
    PHONE_NUMBER: AgAteXQmDZ0oCNq9KkIwTTu8nLtyluOiKleW5aKqYymur2RAX6ssZQtXdBqHnPX9WROMrbGfBY1R1872wRT+l5G4Lkm8QLQU2avbKJXmk8H9dmoPAr8F+dKfcTLKO1vwEykdqguxtzg6uJg4wByKrgbc5pzksTitGWqvSUc8vR+LiMlfClUp5pRnPAFIh8qftSAwqbU6WJSFnSlv1IyFp8zS6Vmvs45OGg7skcLDmFO9OzZwW+A4evWW3EiLzu5YrnfGXLnWwx/amRVEKjkX0IL74xGIyZFdBKKSjvXDaYjaYzIu0EdQbmxllmqlek7fmJ79DRsVKBadPGPvYXES6hjKirEHMoZOxsPGRss/fZveB0YT6v1vcmK5mR6izX2qAovRjnNPm21S50UpvcTPW4BYoHRMSwGFGeYykrnf6oaCMT4wn1gNDhwctanFEbHUACjJgMt5Q/T6Unsdm2Ukt697WhdtsLmkT9TL/DG40t8E60I26l5+w2BkAyVOC67oreHIbOQESRjAUNfq7NCVqh+BzRy9OANPFFckkx+vWNcMPDuxM+JwY7JRhAowakRbHqc3mUi64CC3SLkfKOSQRgfaOMOyvr0e7hg+8snDsj2LRNniO95pSA8tGSR/wtnR23R1H2XEfx2IZKK/dYixM17AFJKw9q3thGJK3OcNPws/P7tmOriIJ83N5SpWuTy9XKbDWZ0QssU6WNQD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gongik-ars-phone2-secret
      namespace: haenu
    type: Opaque