apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-argo-cd-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/acme-dns01-provider: cf-dns
spec:
  tls:
  - hosts:
    - argo.haenu.xyz
    secretName: argocd-argo-cd-server-tls
  rules:
  - host: argo.haenu.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argocd-argo-cd-server
            port:
              number: 80
