apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unithon-frontend-dev
  namespace: argocd
spec:
  destination:
    name: vke-haenu
    namespace: unithon
    server: ''
  source:
    path: apps/unithon/frontend-dev
    repoURL: 'https://github.com/dokdo2013/haenu-cluster'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
