apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuk-haenu-com
  namespace: legacy
  labels:
    app: cuk-haenu-com
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cuk-haenu-com
  template:
    metadata:
      labels:
        app: cuk-haenu-com
    spec:
      containers:
      - name: cuk-haenu-com
        image: hyeonwoo5342/cuk-haenu-com:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: '150Mi'
            cpu: '30m'
          requests:
            memory: '150Mi'
            cpu: '30m'
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cuk-haenu-com
  namespace: legacy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cuk-haenu-com
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
