apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bash-plus-server-ingress
  namespace: api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.bash.plus
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: bash-plus-server
                port:
                  number: 8080
