apiVersion: apps/v1
kind: Deployment
metadata:
  name: junharry-test
  namespace: leaven
  labels:
    app: junharry-test
spec:
  selector:
    matchLabels:
      app: junharry-test
  template:
    metadata:
      labels:
        app: junharry-test
    spec:
      containers:
      - name: junharry-test
        image: hyeonwoo5342/junharry-test:18
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: '200Mi'
            cpu: '100m'
          requests:
            memory: '200Mi'
            cpu: '100m'
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: junharry-test
  namespace: leaven
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: junharry-test
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
