apiVersion: apps/v1
kind: Deployment
metadata:
  name: inpyeongo
  namespace: haenu
  labels:
    app: inpyeongo
spec:
  selector:
    matchLabels:
      app: inpyeongo
  template:
    metadata:
      labels:
        app: inpyeongo
    spec:
      containers:
      - name: inpyeongo
        image: hyeonwoo5342/inpyeongo:1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: '150Mi'
            cpu: '100m'
          requests:
            memory: '150Mi'
            cpu: '100m'
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inpyeongo
  namespace: haenu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inpyeongo
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
