apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaven-api-temp
  namespace: api
  labels:
    app: leaven-api-temp
spec:
  selector:
    matchLabels:
      app: leaven-api-temp
  template:
    metadata:
      labels:
        app: leaven-api-temp
    spec:
      containers:
        - name: leaven-api-temp
          image: hyeonwoo5342/leaven-api-temp:4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "100Mi"
              cpu: "30m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: leaven-api-temp-secret
      #      affinity:
      #        nodeAffinity:
      #          requiredDuringSchedulingIgnoredDuringExecution:
      #            nodeSelectorTerms:
      #            - matchExpressions:
      #              - key: vke.vultr.com/node-pool
      #                operator: In
      #                values:
      #                - main-node-pool
      imagePullSecrets:
        - name: dockerhub-secret
