apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: junharry-test
  namespace: argocd
spec:
  destination:
    name: vke-haenu
    namespace: leaven
    server: ''
  source:
    path: apps/leaven/junharry-test
    repoURL: 'https://github.com/dokdo2013/haenu-cluster'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
