apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-musicbook-be
  namespace: api
  labels:
    app: dev-musicbook-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-musicbook-be
  template:
    metadata:
      labels:
        app: dev-musicbook-be
    spec:
      containers:
      - name: dev-musicbook-be
        image: hyeonwoo5342/dev-musicbook-be:5
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: '250Mi'
            cpu: '250m'
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-secret
        

