apiVersion: v1
kind: Service
metadata:
  name: dev-musicbook-fe
  namespace: haenu
  labels:
    app: dev-musicbook-fe
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: dev-musicbook-fe
